# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8b9538ef286737db9e4714f7bbb88070af409bc06a86fb8876e8d19a7441c7f422e24876a705d54ffe896b24f27da1627913fe4c22b1b489664d7852e4326cfc

test:
  secret_key_base: a3cd7a59d960f7e207905f835256c31efd34b243141a4b15e5f0812e4cf35c66d035b25055e71196e9d7229da18fb3b94a0b7e0ba7ab755dfb4244a153bbe66d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
